### ISSUE TITLE
custom embeddings in BERTopic evaluation

### ISSUE THREAD

**Issue by lakshmiPKumar** [MaartenGr/BERTopic_evaluation#2]
Hi Maarten
Is it possible to run custom embeddings other than sentence transformers using Evaluation.ipynb ? I wanted to try embeddings from flair.

**Comment by MaartenGr** [comment]
Yes, you would only need to replace the following steps with that of Flair:

```python
# Extract embeddings
model = SentenceTransformer("all-mpnet-base-v2")
embeddings = model.encode(data, show_progress_bar=True)
```
