### ISSUE TITLE
Question about OOV words 

### ISSUE THREAD

**Issue by nguyenkhoihoang** [MaartenGr/BERTopic_evaluation#7]
```
if not self.timestamps:
            all_words = [word for words in self.data.get_corpus() for word in words]
            bertopic_topics = [
                [
                    vals[0] if vals[0] in all_words else all_words[0]
                    for vals in model.get_topic(i)[:10]
                ]
                for i in range(len(set(topics)) - 1)
            ]

            output_tm = {"topics": bertopic_topics}
```
Hi, I don't understand why at this part there might be an "else", and why would you specifically choose all_words[0] to replace it. From my understanding, there isn't online learning in this part, so why can there be new words?

Thank you for your assistance.

**Comment by MaartenGr** [comment]
What is happening here is that the model does not allow tokenizing the topic words properly, to account for that, an essentially random word was added to the representation. This typically lowers the evaluation for BERTopic a bit but I preferred that over nudging it toward better evluation. This could definitely be better, as there are ways to circumvent the tokenization issue, but it happens quite rarely.

**Comment by nguyenkhoihoang** [comment]
I see, thank you. I was following your evaluation of BERTopic on a less standard dataset, which produced many words not found in all_words, so I was confused. Your answer clarified that, thanks!
